### ISSUE TITLE
Apply Profile: ERROR: Invalid XBee profile: invalid literal for int() with base 10: '100A'

### ISSUE THREAD

**Issue by JoelDorrington** [digidotcom/xbee-python#177]
Using the digi-xbee library installed by pip (1.3.0) the error in the title is thrown when trying to load a profile from a zip file.

**ERROR: Invalid XBee profile: invalid literal for int() with base 10: '100A'**

It appears it's trying to read the firmware version from both the XML file and the xbee device as decimal when it is in fact hexadecimal. I tinkered with the source code to confirm. The source downloaded by pip does not match the latest code in this repo which now explicitly treats it as base 16.

To get this fix I tried downloading the repo source code and installing as per the README but that led to even more problems, I can elaborate if needed.

**Comment by tatianaleon** [comment]
Hi @JoelDorrington,

Thanks for reporting this issue. It is already fixed in master (see commit [814c5e9](https://github.com/digidotcom/xbee-python/commit/814c5e999a4752a121d0a6b445c5d1eead3a862e)) and will be included in the next release.

If you have problems working with the source code in master, please let us know.

Sorry for the inconvenience.

Best regards.
