### ISSUE TITLE
ApiFrameType is not iterable

### ISSUE THREAD

**Issue by cricc78** [digidotcom/xbee-python#242]
We have a Xbee3 LTE Cat 1 (Verizon) device and we're using this python library to send HTTP POSTs over a TCP socket. 

The problem is that the socket.connect fails even if we use the exact TCP Socket example code with no modification. Here's an example of the error:

![image](https://user-images.githubusercontent.com/21106278/120684737-0cca5c80-c46d-11eb-81bd-f0a450d145ba.png)

This happens even if we run other sample code, such as the sms send example. In this case, the sms successfully sends, but we get the "ApiFrameType is not iterable" error just like we get when running the TCP socket example. The library seems to have an issue processing the response packets, or there is no response packet.

We've installed this library from source, so that we could get the latest commits that aren't in v1.4 (those seem to fix the CellularDevice not working at all).

Has anyone encountered this issue?

**Comment by tatianaleon** [comment]
Hi @cricc78,

Thanks for reporting. This issue is fixed in master (see commit https://github.com/digidotcom/xbee-python/commit/6598e5a14fd6545f9360717bac32220dbd45c900) and will be included in the next release.

In the meantime, you can download the source code from the master branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
