### ISSUE TITLE
Device read data returns None

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [digidotcom/xbee-python#63]
Hi all,

I'm trying to use `read_data()` to read data from a coordinator connected to USB but I get not data. The code that I'm using is the following:

```
from digi.xbee.devices import XBeeDevice
PORT = "/dev/ttyUSB0"
BAUD_RATE = 9600
device = XBeeDevice(PORT, BAUD_RATE)
device.open()
device.flush_queues()
xbee_message = device.read_data()
```
The xbee_message is allways None. I have checked with XCTU that from the console that I recive data  but the python code it is not working. The Corrdinatore is in AP=1 and the apioutput mode is  NATIVE.

Best,

Lorenzo

**Comment by tatianaleon** [comment]
Hi @LorenzoBottaccioli,

Try to specify a timeout when using `read_data()` method, otherwise it will check if there is data at that moment and, if not, it will return `None` immediately (see [Polling for data](https://xbplib.readthedocs.io/en/latest/user_doc/communicating_with_xbee_devices.html#polling-for-data)) The value of `timeout` will depend on your setup.
For example, for a timeout of 2 seconds:

```python
from digi.xbee.devices import XBeeDevice
PORT = "/dev/ttyUSB0"
BAUD_RATE = 9600
device = XBeeDevice(PORT, BAUD_RATE)
device.open()
device.flush_queues()
xbee_message = device.read_data(timeout=2)
```

Anyway, for receiving data you can also register a callback using `add_data_received_callback()`, see [Data reception callback](https://xbplib.readthedocs.io/en/latest/user_doc/communicating_with_xbee_devices.html#data-reception-callback).

Best Regards.
