### ISSUE TITLE
[FEATURE REQUEST] if block in PacketListener.__add_packet_queue should be elif

### ISSUE THREAD

**Issue by orenbell-nidec** [digidotcom/xbee-python#71]
See the first two `if` blocks in this code segment

    if xbee_packet.get_frame_type() in [ApiFrameType.RECEIVE_PACKET, ApiFrameType.RX_64, ApiFrameType.RX_16]:
        if self.__data_xbee_queue.full():
            self.__data_xbee_queue.get()
        self.__data_xbee_queue.put_nowait(xbee_packet)
    # Explicit packets.
    if xbee_packet.get_frame_type() == ApiFrameType.EXPLICIT_RX_INDICATOR:
        if self.__explicit_xbee_queue.full():
            self.__explicit_xbee_queue.get()
        self.__explicit_xbee_queue.put_nowait(xbee_packet)
        # Check if the explicit packet is 'special'.
        if self.__is_special_explicit_packet(xbee_packet):
            # Create the non-explicit version of this packet and add it to the queue.
            self.__add_packet_queue(self.__expl_to_no_expl(xbee_packet))
    # IP packets.
    elif xbee_packet.get_frame_type() == ApiFrameType.RX_IPV4:
    ...

The conditions for the first and second if statements are mutually exclusive, so the second can be changed to elif for optimal performance.

**Comment by tatianaleon** [comment]
Hi @orenbell-nidec,

Thanks for reporting this issue. It is already fixed in `master` (see commit https://github.com/digidotcom/xbee-python/commit/76f9d072c027da34ed756a3f0424cb39d99e92ba) and will be included in the next release.

In the meantime, you can download the source code from the master branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
