### ISSUE TITLE
[FEATURE REQUEST] Add method to RemoteXBeeDevice to transmit data

### ISSUE THREAD

**Issue by orenbell-nidec** [digidotcom/xbee-python#74]
When I have a RemoteXBeeDevice object I want to transmit data to, it's a little cumbersome to reference the local device's send_data method, and then pass the RemoteXBeeDevice to that.

    remote.get_local_xbee_device().send_data(remote, data)

I propose a new wrapper method in RemoteXBeeDevice that eliminates some of the redundancy

    class RemoteXBeeDevice:
        ....
        def send_data(self, data, transmit_options=TransmitOptions.NONE.value):
            _local_xbee_device.send_data(self, data, transmit_options)

#### Before:

    remote.get_local_xbee_device().send_data(remote, data)

#### After:

    remote.send_data(data)

**Comment by tatianaleon** [comment]
Hi @orenbell-nidec 

Thanks for your suggestion, but I'm afraid we are not going to include it. Let me explain why:

When working with XBee devices, it is **impossible to send anything from one remote node to another remote node**. Not for the library, it is impossible using anything.
You can only send data **from the local node** (the one you access using the serial connection) **to any remote in the same network**.

Taking into account the following code
```python
local.send_data(remote, data)
```
means, `local` sends `data` to `remote`.

Something like:
```python
remote.send_data(data)
```
is misleading, because you can think that `remote` sends `data`, and we know that is not possible :-).

Best Regards.
